version: '3.8'

services:
  family-mapping-app:
    image: mkeathley75028/family-mapping-app:latest
    ports:
      - "8765:8765"
    volumes:
      # Mount datasets directory to persist data between container restarts
      - ./datasets:/app/datasets
    restart: unless-stopped
    container_name: family-mapping-app
    environment:
      - FLASK_ENV=production 