# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app_standalone.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates/map.html', 'templates'),
        ('sample_family_addresses.csv', '.'),
    ],
    hiddenimports=[
        'flask',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.base',
        'pandas.core',
        'pandas.core.arrays',
        'pandas.core.dtypes',
        'pandas.io',
        'pandas.io.formats',
        'pandas.io.common',
        'pandas.io.parsers',
        'pandas.io.parsers.readers',
        'geopy',
        'geopy.geocoders',
        'geopy.geocoders.nominatim',
        'geopy.extra',
        'geopy.extra.rate_limiter',
        'numpy',
        'numpy.core',
        'numpy.core._multiarray_umath',
        'pytz',
        'dateutil',
        'dateutil.parser',
        'six',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FamilyMappingApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
) 